[package]
name = "bower-internal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
image-rs = ["bower-image"]

[dependencies]
bower-image = { path = "../bower-image", optional = true }
