[package]
name = "bower-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
bower-core = { path = "../bower-core" }
image = { version = "0.24.3", optional = true }
