[package]
name = "bower-core"
version = "0.1.0"
authors = ["leonzhao"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
